version: '3'

services:
  tenpo-postgres:
    image: postgres:15.3-bullseye
    container_name: tenpo-postgres
    environment:
      - POSTGRES_DB=tenpo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5432:5432

  tenpo-redis:
    image: redis:latest
    container_name: tenpo-redis
    ports:
      - 6379:6379

  app:
    image: simongs89/tenpo-api
    # image: tenpo-app
    # build: .
    container_name: tenpo-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tenpo-postgres:5432/tenpo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATA_REDIS_HOST=tenpo-redis
      - SPRING_DATA_REDIS_PORT=6379