version: '3'

services:
  db:
    image: postgres:15.3-bullseye
    container_name: tenpo-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - APP_DB_NAME=tenpo
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  cache:
    image: redis:latest
    container_name: tenpo-cache
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.12
      - REDIS_VERSION=6.0.6
      - REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-6.0.6.tar.gz
      - REDIS_DOWNLOAD_SHA=12ad49b163af5ef39466e8d2f7d212a58172116e5b441eebecb4e6ca22363d94
    ports:
      - 6379:6379
  app:
    image: tenpo-app
    build: .
    restart: always
    container_name: tenpo-app
    depends_on:
      - db
      - cache
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - REDIS_HOST_NAME=cache
      - REDIS_PORT=6379